-- 1. Bảng USER
CREATE TABLE USERS (
    userID VARCHAR(50) PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    fullName VARCHAR(255) NOT NULL,
    phoneNum VARCHAR(20),
    role VARCHAR(20) DEFAULT 'CUSTOMER' CHECK (role in ('CUSTOMER', 'ADMIN')),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_email_format CHECK (email ~* '^[A-Za-z0-9._%-]+@[A-Za-z0-9.-]+[.][A-Za-z]+$')
);

-- 2. Bảng AUTH_TOKENS
CREATE TABLE AUTH_TOKENS (
    tokenID SERIAL PRIMARY KEY,
    userID VARCHAR(50) NOT NULL REFERENCES USERS(userID) ON DELETE CASCADE,
    refreshToken VARCHAR(255) UNIQUE NOT NULL,
    userAgent TEXT,
    expireAt TIMESTAMP NOT NULL,
    isRevoked BOOLEAN DEFAULT FALSE
);

-- 3. Bảng ADDRESS
CREATE TABLE ADDRESSES (
    addressID SERIAL PRIMARY KEY,
    userID VARCHAR(50) NOT NULL REFERENCES USERS(userID) ON DELETE CASCADE,
    addressLine VARCHAR(255) NOT NULL,
    addressName VARCHAR(100),
    city VARCHAR(100) NOT NULL,
    district VARCHAR(100) NOT NULL,
    isDefault BOOLEAN DEFAULT FALSE
);

-- 4. Bảng ORDER
CREATE TABLE ORDERS (
    orderID SERIAL PRIMARY KEY,
    userID VARCHAR(50) NOT NULL REFERENCES USERS(userID),
    status VARCHAR(50) DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED')),
    totalAmount INTEGER NOT NULL,
    shippingAddr JSONB NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_total_amount CHECK (totalAmount >= 0)
);

-- 5. Bảng ITEM
CREATE TABLE ITEMS (
    itemID SERIAL PRIMARY KEY,
    orderID INTEGER NOT NULL REFERENCES ORDERS(orderID) ON DELETE CASCADE,
    productID VARCHAR(50) NOT NULL,
    sku VARCHAR(50) NOT NULL,
    productName VARCHAR(255) NOT NULL,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    unitPrice INTEGER NOT NULL CHECK (unitPrice >= 0)
);

-- 6. Bảng PAYMENT
CREATE TABLE PAYMENTS (
    paymentID SERIAL PRIMARY KEY,
    orderID INTEGER UNIQUE NOT NULL REFERENCES ORDERS(orderID) ON DELETE CASCADE,
    method VARCHAR(50) NOT NULL CHECK (method IN ('COD', 'BANKING', 'E_WALLET')),
    status VARCHAR(50) DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED')),
    transactionDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 7. Bảng INVENTORY
CREATE TABLE INVENTORY (
    inventoryID SERIAL PRIMARY KEY,
    productID VARCHAR(50) NOT NULL,
    sku VARCHAR(100) UNIQUE NOT NULL,
    stockQuantity INTEGER NOT NULL,
    lastUpdated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_stock_positive CHECK (stockQuantity >= 0)
);